appInventario/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.loginuser, name='login'),
    path('logout', views.logoutuser, name='logout'),
    path('dependencia/', include('dependencias.urls')),
    path('rfid/', include('rfid.urls')),
    path('bienes/', include('bienes.urls')),
    path('reportes/', include('reportes.urls')),
    path('admin/', admin.site.urls),
]

rfid/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='rfid'),
    path('<str:room_name>/', views.room, name='room'),
]

bienes/models.py
from django.db import models

# Create your models here.

from trabajadores.models import Cargotrabajador


# Create your models here.
class Bien_Universidad(models.Model):
    """docstring for Bien_Universidad"""
    select_status = (('1', 'Activo Fijo'), ('2', 'Baja'))
    select_type_active = (('1', 'Activo depreciable'),
                          ('2', 'Activo No Depreciable'))
    select_doc_adqui = (('031', ' O/C - Guia --> FECHA_COMPRA,VALOR_COMPRA,NRO_ORDEN'),
                        ('045', 'Nea --> NRO_DOCUMENTO,VALOR_NEA,FECHA_NEA'))
    slect_type_Transnea = [(3, 'NEA-Ingreso Produccion'),
                           (4, 'NEA-Ingreso Donacion'),
                           (5, 'NEA-Transf. Externa'),
                           (8, 'NEA-Diferenc. Inventario'),
                           (9, 'NEA - Otros')]
    slect_flag_item = (('N', 'No'), ('S', 'Si'))
    slect_status_coserv = (('1', 'Bueno'), ('2', 'Regular'), ('3', 'Malo'))

    SEC_EJEC = models.IntegerField()
    TIPO_MODALIDAD = models.IntegerField()
    SECUENCIA = models.IntegerField()
    CODIGO_ACTIVO = models.CharField(max_length=24, unique=True)
    ESTADO = models.CharField(choices=select_status,
                              default='1', max_length=1, null=False)
    TIPO_BIEN = models.CharField(max_length=1)
    GRUPO_BIEN = models.CharField(max_length=2)
    CLASE_BIEN = models.CharField(max_length=2)
    FAMILIA_BIEN = models.CharField(max_length=4)
    ITEM_BIEN = models.CharField(max_length=4)
    DESCRIPCION = models.CharField(max_length=200)
    TIPO_ACTIVO = models.CharField(
        choices=select_type_active, default='1', max_length=1, null=False)
    TIPO_DOC_ADQUISICION = models.CharField(
        choices=select_doc_adqui, default='031', max_length=3)
    TIPO_MOV_NEA = models.CharField(max_length=1)
    TIPO_TRAN_NEA = models.IntegerField(
        choices=slect_type_Transnea, default=3)
    NRO_DOCUMENTO = models.CharField(max_length=10)
    VALOR_NEA = models.DecimalField(decimal_places=6, max_digits=16)
    FECHA_NEA = models.DateField()
    NRO_ORDEN = models.PositiveIntegerField()
    VALOR_COMPRA = models.DecimalField(decimal_places=6, max_digits=16)
    FECHA_COMPRA = models.DateField()
    TIPO_DOC_ALTA = models.CharField(max_length=3)
    NRO_PECOSA = models.IntegerField()
    FECHA_ALTA = models.DateField()
    SEDE = models.IntegerField()
    CENTRO_COSTO = models.CharField(max_length=15)
    EMPLEADO_RESPONSABLE = models.CharField(max_length=15)
    EMPLEADO_FINAL = models.CharField(max_length=15)
    TIPO_UBICAC = models.IntegerField()
    SUBTIPO_UBICAC = models.CharField(max_length=3)
    CARACTERISTICAS = models.CharField(max_length=300, null=True, blank=True)
    MODELO = models.CharField(max_length=40, null=True, blank=True)
    MEDIDAS = models.CharField(max_length=30, null=True, blank=True)
    NRO_SERIE = models.CharField(max_length=20, null=True, blank=True)
    FLAG_ITEM_ESNI = models.CharField(
        choices=slect_flag_item, default='N', max_length=1)
    MARCA = models.DecimalField(decimal_places=0, max_digits=5)
    COD_MODELO = models.DecimalField(
        decimal_places=0, max_digits=3, null=True, blank=True)
    ESTADO_ACTUAL = models.CharField(max_length=1)
    ESTADO_CONSERV = models.CharField(
        choices=slect_status_coserv, default='1', max_length=1)
    FECHA_MOVIMTO = models.DateField()
    PROVEEDOR = models.DecimalField(
        decimal_places=0, max_digits=5, null=True, blank=True)
    COD_ALMACEN = models.CharField(max_length=3)
    SEC_ALMACEN = models.CharField(max_length=3)
    FLAG_ETIQUETA = models.CharField(max_length=1)
    FECHA_ETIQUET = models.DateField(null=True)
    VALOR_INICIAL = models.DecimalField(decimal_places=2, max_digits=16)
    VALOR_DEPREC = models.DecimalField(decimal_places=2, max_digits=16)
    INVENT_SCANER = models.CharField(max_length=1)
    CLASIFICADOR = models.CharField(max_length=20)
    ANIO_EJE = models.DecimalField(decimal_places=0, max_digits=4)
    SUB_CTA = models.CharField(max_length=8)
    MAYOR = models.CharField(max_length=4)
    CODIGO_BARRA = models.CharField(max_length=15, blank=True, null=True)
    OBSERVACIONES = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        """docstring for Meta"""

        verbose_name_plural = "Bienes Universidad"

    def __str__(self):
        return self.CODIGO_ACTIVO


class Verificacion(models.Model):
    nombre_verificacion = models.CharField(max_length=20)
    documento = models.CharField(max_length=100)
    fecha_inicio = models.DateTimeField()
    fecha_finalizacion = models.DateTimeField()
    estado_verificacion = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Verificaciones"

    def __str__(self):
        return self.nombre_verificacion


class Bien_Trabajador(models.Model):
    """docstring for Bien_Trabajador"""
    bien_universidad = models.ForeignKey(
        Bien_Universidad, on_delete=models.PROTECT)
    cargotrabajador = models.ForeignKey(
        Cargotrabajador, on_delete=models.PROTECT)
    fecha = models.DateTimeField()
    estado_asignacion = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = "Bienes asociados al trabajador"

    def __str__(self):

        return self.cargotrabajador.trabajador.apellidos+"-"+self.bien_universidad.CODIGO_ACTIVO


class Bien_verificacion(models.Model):
    """docstring for Bien_verificacion"""

    verificacion = models.ForeignKey(Verificacion, on_delete=models.PROTECT)
    bien_trabajador = models.ForeignKey(
        Bien_Trabajador, on_delete=models.PROTECT)
    fecha_verificacion = models.DateTimeField()
    estado_bien = models.CharField(max_length=1)
    observacion = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Verificación Bienes"

    def __str__(self):

        return str(self.verificacion.id)

    def name_verification(self):
        return self.verificacion.nombre_verificacion

    def getrabajador(self):
        return self.bien_trabajador.cargotrabajador.trabajador.apellidos

    def getcargo(self):
        return self.bien_trabajador.cargotrabajador.cargo.nombre_cargo

rfid/views.py
import logging
from django.shortcuts import render, redirect
#from dependencias.models import Oficina
from trabajadores.models import (Trabajador, Cargotrabajador)
from bienes.models import (Bien_Trabajador, Verificacion)

# Create your views here.


def index(request):
    # return render(request,'rfid/index.html',{})
    logging.info(request.POST)
    idoficina = request.POST.get('office')
    idcargotrabajador = request.POST.get('worked')
    # trabajador=Trabajador.objects.get(pk=idtrabajador)
    # oficina=Oficina.objects.get(pk=idoficina)
    cargotrabajador = Cargotrabajador.objects.get(pk=idcargotrabajador)
    bienes_a_cargo = Bien_Trabajador.objects.filter(
        cargotrabajador=cargotrabajador)
    verificion_programado = Verificacion.objects.filter(
        estado_verificacion=True)

    total_retorno = len(verificion_programado)

    # ultima verificacion programada
    if total_retorno > 0:
        # recuperando primer elemento...que representa a la ultima programacion
        verificion_programado = verificion_programado[0]

    return render(request, 'rfid/view_bienes.html',
                  {'room_name': "read",
                   'bienes_data': bienes_a_cargo,
                   'verificacion': verificion_programado,
                   'estado': total_retorno})

    # return redirect('room','read')


def room(request, room_name):

    idoficina = request.POST.get('office')
    idtrabajador = request.POST.get('worked')
    print(request.POST)

    print(str(idoficina)+"->"+str(idtrabajador))

    # return render (request,'rfid/room.html',
    return render(request, 'rfid/view_bienes.html',
                  {'room_name': room_name})

rfid/templates/rfid/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/rfid/' + roomName + '/';
        };
    </script>
</body>
</html>

rfid/templates/rfid/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>

    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
    
    <input id="commnad-open-submit"  type="button" value="open"/>
    <input id="commnad-close-submit"  type="button" value="close"/>
    <input id="commnad-readone-submit"  type="button" value="read-one"/>
    <input id="commnad-readmult-submit"  type="button" value="read-mult"/>
    
</body>
<script>
    var roomName = "{{ room_name|escapejs }}";

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/rfid/' + roomName + '/');

    chatSocket.onmessage = async function(e) {
        var data = await JSON.parse(e.data);
        var message = data['message'];

        if(message!="open" && (message!="close" && (message!="read-one" && (message!="read-mult" && message!="stop"))))
        {
          document.querySelector('#chat-log').value += (message + '\n');
        }

        
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick =async function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        await chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
    //operaciones para activar el rfid desde la web
    

     
    document.querySelector('#commnad-open-submit').onclick =async function(e) {
        
        var comando = this.value;
        await chatSocket.send(JSON.stringify({
            'message': comando
        }));
        //alert("Hola open")
    };

    document.querySelector('#commnad-close-submit').onclick =async function(e) {
        
        var comando = this.value;
        await chatSocket.send(JSON.stringify({
            'message': comando
        }));

        //alert("Hola close")
    };

     document.querySelector('#commnad-readone-submit').onclick =async function(e) {
        
        var comando = this.value;
        await chatSocket.send(JSON.stringify({
            'message': comando
        }));
       // alert("Hola read one")
    };
    
     document.querySelector('#commnad-readmult-submit').onclick =async function(e) {
        
         var comando = this.value;
       // console.log(comando)
        await chatSocket.send(JSON.stringify({
            'message': comando
        }));
       
        
       if (comando=="stop") 
       {
          document.querySelector('#commnad-readmult-submit').value="read-mult";
       }
       else
        {
            document.querySelector('#commnad-readmult-submit').value="stop";

       }
        
     
    };

</script>
</html>

rfid/templates/rfid/view_bienes.html
{% extends 'base.html' %}

{% block title %}Bienes responsable{% endblock %}

{% block body_block %}

<div class="container-fluid">
    <table class="table table-sm table-bordered  table-responsive-xl" id="tb_bienes">
        <thead>
            <tr>
                <th scope="col">Item</th>
                <th scope="col">Codigo Patrimonial</th>
                <th scope="col">Codigo Interno</th>
                <th scope="col">Tipo de bien</th>
                <th scope="col">Detalle tecnico</th>
                <th scope="col">Fecha de Adquisicion</th>
                <th scope="col">Estado</th>
                <th scope="col">Valor del bien</th>
                <th scope="col">Usuario</th>
                <th scope="col">Existe?</th>
            </tr>
        </thead>
        <tbody>
            {% for bien in bienes_data %}
            <tr>

                <td>
                    {{bien.id}}
                </td>
                <td>
                    {{bien.bien_universidad.CODIGO_ACTIVO}}
                </td>
                <td>
                    {{bien.bien_universidad.ITEM_BIEN}}
                </td>
                <td>
                    {{bien.bien_universidad.TIPO_BIEN}}
                </td>
                <td>
                    {{bien.bien_universidad.DESCRIPCION}}
                </td>
                <td>
                    {{bien.bien_universidad.FECHA_COMPRA}}
                </td>
                <td>
                    {{bien.bien_universidad.ESTADO_ACTUAL}}
                </td>
                <td>
                    {{bien.bien_universidad.VALOR_INICIAL}}
                </td>
                <td>
                    {{bien.bien_universidad.EMPLEADO_RESPONSABLE}}
                </td>
                <td>
                    En espera...
                </td>

            </tr>

            {% endfor %}

        </tbody>
    </table>
</div>

<div class="container-fluid">
    {% if estado == 1 %}

    <input id="commnad-open-submit" type="button" value="open" style="display: none;" />
    <input id="commnad-close-submit" type="button" value="close" style="display: none;" />
    <input id="commnad-readone-submit" type="button" value="Escanear" class="btn btn-primary" />
    <input id="commnad-readmult-submit" type="button" value="read-mult" style="display: none;" />
    <input id="sent_verification" type="button" value="Guardar verificacion" class="btn btn-primary" />

    {% else %}

    <label class="warning">*No existe una programacion de verificacion o estan activos multiples verificaciones</label>

    {% endif %}
</div>

<div class="container-fluid">
    <form id="submit_verification" action="../bienes/process_verification" method="post">
        {% csrf_token %}

        <input type="hidden" id="id_verificacion" name="check_program" value="{{verificacion.id}}">
        <input type="hidden" id="id_data_send" name="data_verifications" value="">
    </form>
</div>
<script>
    const id_verificacion = '{{verificacion.id}}';
    const actions = {
        OPEN: 'Open',
        CLOSE: "Close",
        READ_ONE: "ReadOne",
        KEEP_READING: "KeepReading",
        STOP: "Stop"
    }
    let roomName = "{{ room_name|escapejs }}";
    console.log(`roomName: ${roomName}`)


    let chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/rfid/' + roomName + '/');

    chatSocket.onmessage = onSocketMessage;

    chatSocket.onclose = function (responseMessage) {
        console.error('Chat socket closed unexpectedly');
    };

    // document.querySelector('#chat-message-input').focus();
    // document.querySelector('#chat-message-input').onkeyup = function(e) {
    //     if (e.keyCode === 13) {  // enter, return
    //         document.querySelector('#chat-message-submit').click();
    //     }
    // };

    // document.querySelector('#chat-message-submit').onclick =async function(e) {
    //     let messageInputDom = document.querySelector('#chat-message-input');
    //     let message = messageInputDom.value;
    //     await chatSocket.send(JSON.stringify({
    //         'message': message
    //     }));

    //     messageInputDom.value = '';
    // };
    //operaciones para actilet el rfid desde la web

    function initBindings() {
        document.querySelector('#commnad-open-submit').onclick = async function (e) {
            let comando = this.value;
            await chatSocket.send(JSON.stringify({
                'action': actions.OPEN
            }));
        };

        document.querySelector('#commnad-close-submit').onclick = async function (e) {
            let comando = this.value;
            await chatSocket.send(JSON.stringify({
                'action': actions.CLOSE
            }));
        };

        document.querySelector('#commnad-readone-submit').onclick = async function (e) {
            let comando = this.value;
            await chatSocket.send(JSON.stringify({
                'action': actions.READ_ONE
            }));
            // esta programaci'on es  para la simulacion...debe ir en guardar verificacion
        };

        document.querySelector('#commnad-readmult-submit').onclick = async function (e) {
            let comando = this.value;
            await chatSocket.send(JSON.stringify({
                'action': actions.KEEP_READING
            }));

            // if (comando == "stop") {
            //   document.querySelector('#commnad-readmult-submit').value = "read-mult";
            // }
            // else {
            //   document.querySelector('#commnad-readmult-submit').value = "stop";
            // }
        };

        $(document.body).on("click", "#sent_verification", sendVerification);
    }

    async function onSocketMessage(responseMessage) {
        console.log(`From service: ${responseMessage.data}`)
        let data = await JSON.parse(responseMessage.data);
        let response = data['message'];
        if (Object.values(actions).includes(response.action)) {
            return false;
        }

        let responseread = response;
        let encontrado = 0;

        $("#tb_bienes tbody tr").each(function (index) {
            let codigo_bien, estado_verificacion;
            encontrado = 0;
            $(this).children("td").each(function (index2) {
                codigo_bien = "";
                if (index2 == 1) {
                    codigo_bien = $(this).text().trim();
                    if (response.filter(b => b.EPC == codigo_bien).length > 0) {
                        encontrado = 1;
                        console.log(`${codigo_bien} encontrado`)
                    }
                }
                switch (index2) {
                    case 9:
                        if (encontrado == 1) {
                            console.log(`encontrado`)
                            $(this).html("Existe")
                            encontrado = 0;
                        }

                        break;
                }
            })
        })
    }

    function sendVerification() {
        let lista_bienes = [];
        $("#tb_bienes tbody tr").each(function (index) {

            let id_bien, estado_verificacion;

            $(this).children("td").each(function (index2) {
                switch (index2) {
                    case 0:
                        id_bien = $(this).text();

                        break;
                    case 9:
                        estado_verificacion = $(this).text()

                        break;
                }
            });

            const item_bien = { "id": id_bien.trim(), "estado": estado_verificacion.trim(), "obs": "todo normal" }
            lista_bienes.push(item_bien);
        })

        showLoading(true);
        postData('../bienes/process_verification', {
            id_verificacion,
            lista_bienes
        })
            .catch((e) => {
                console.error(e);
            })
            .finally(() => {
                showLoading(false);
            });
    }

    initBindings();
</script>

{% endblock %}